version: '3.8'

services:
  db:
    image: ahmedwaleed95/my-postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahmed2003
      POSTGRES_DB: eden
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./eden.backup:/docker-entrypoint-initdb.d/eden.backup
    ports:
      - "5432:5432"

  app:
    image: ahmedwaleed95/my-code-app:latest
    depends_on:
      - db
    environment:
      PGPASSWORD: ahmed2003
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

volumes:
  pgdata:
